import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            padding: "1rem",
            backgroundColor: "#f0f0f0",
            marginBottom: "1rem",
          }}
        >
          <nav>
            <Link href="/" style={{ marginRight: "10px" }}>
              Hjem
            </Link>
            <Link href="/catalogue" style={{ marginRight: "10px" }}>
              Om Oss
            </Link>
            {/*homepage*/}
            <Link href="/contact" style={{ marginRight: "10px" }}>
              Tjenester
            </Link>
            <Link href="/contact" style={{ marginRight: "10px" }}>
              Tjenester
            </Link>
            {/* Link to a dynamic blog post example */}
            <Link href="/blog/itemid">Blogginnlegg Eksempel</Link>
          </nav>
        </header>
        <main>{children}</main>
        <footer
          style={{
            padding: "1rem",
            backgroundColor: "#f0f0f0",
            marginTop: "1rem",
            textAlign: "center",
          }}
        >
          <p>
            &copy; {new Date().getFullYear()} Mitt Prosjekt AS. Alle rettigheter
            reservert.
          </p>
        </footer>
      </body>
    </html>
  );
}
